#spring.application.name=productservice
#server.port=8081
## application.properties (for Product & Order Services)
#spring.datasource.url=jdbc:mysql://localhost:3306/shoppingdb
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update

spring:
  application:
    name: order-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingdb
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082

#eureka:
#    client:
#        service-url:
#            defaultZone: http://localhost:8761/eureka/
#        register-with-eureka: true
#        fetch-registry: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true